apiVersion: apps/v1
kind: Deployment
metadata:
    name: requests-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: requests
    template:
        metadata:
            labels:
                app: requests
        spec:
            containers:
                - name: requests
                  image: tommyling79/book-trading-requests
                  env:
                      - name: NATS_URL
                        value: 'http://nats-srv:4222'
                      - name: NATS_CLUSTER_ID
                        value: 'booktrading'
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MONGO_URI
                        value: mongodb://requests-mongo-srv:27017/requests
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret-book-trading
                                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: requests-srv
spec:
    selector:
        app: requests
    ports:
        - name: requests
          protocol: TCP
          port: 3000
          targetPort: 3000
